### ISSUE TITLE
typos in full version pdf

### ISSUE THREAD

**Issue by rayeaster** [xf97/JiuZhou#2]
https://github.com/xf97/JiuZhou/blob/master/Jiuzhou_Full_version.pdf

**Comment by rayeaster** [comment]
Page 5:
should be `integer truncation`

![image](https://user-images.githubusercontent.com/1487283/94331830-528f7500-0002-11eb-90aa-4df6e7995e1f.png)

**Comment by xf97** [comment]
Thank you for pointing our typos. I will check the whole content as soon as possible to correct the typos.

**Comment by rayeaster** [comment]
a newly published smart contract bug grading reference: 
https://bc.cnvd.org.cn/focus_info?num=e66b7041a4aa3a54e362b4accb076111

**Comment by xf97** [comment]
Ok, let me check this new standard and if necessary I wiil modify the bugs' severity levels.

**Comment by xf97** [comment]
correct typos and check all words in full_verision_pdf.
Closed.
